// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SCMS.Infrastructure;

#nullable disable

namespace SCMS.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SCMS.Domain.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Món chính"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "Đồ uống"
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "Món ăn vặt"
                        },
                        new
                        {
                            CategoryId = 4,
                            CategoryName = "Chưa phân loại"
                        });
                });

            modelBuilder.Entity("SCMS.Domain.MenuItem", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ItemId"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<int>("InventoryQuantity")
                        .HasColumnType("integer");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("ItemId");

                    b.HasIndex("CategoryId");

                    b.ToTable("MenuItems");

                    b.HasData(
                        new
                        {
                            ItemId = 1,
                            CategoryId = 1,
                            Description = "Cơm tấm sườn nướng than",
                            ImageUrl = "https://example.com/comsuon.jpg",
                            InventoryQuantity = 100,
                            IsAvailable = true,
                            Name = "Cơm sườn bì chả",
                            Price = 35000m
                        },
                        new
                        {
                            ItemId = 2,
                            CategoryId = 2,
                            Description = "Đường đen, ít đá",
                            ImageUrl = "https://example.com/trasua.jpg",
                            InventoryQuantity = 50,
                            IsAvailable = true,
                            Name = "Trà sữa trân châu",
                            Price = 25000m
                        });
                });

            modelBuilder.Entity("SCMS.Domain.Notification", b =>
                {
                    b.Property<int>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("NotificationId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<string>("Link")
                        .HasColumnType("text");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("NotificationId");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("SCMS.Domain.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("OrderId"));

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("PickupTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("OrderId");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("SCMS.Domain.OrderItem", b =>
                {
                    b.Property<int>("OrderItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("OrderItemId"));

                    b.Property<int>("ItemId")
                        .HasColumnType("integer");

                    b.Property<int>("OrderId")
                        .HasColumnType("integer");

                    b.Property<decimal>("PriceAtTimeOfOrder")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("OrderItemId");

                    b.HasIndex("ItemId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("SCMS.Domain.Promotion", b =>
                {
                    b.Property<int>("PromotionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PromotionId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("DiscountPercentage")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("PromotionId");

                    b.ToTable("Promotions");
                });

            modelBuilder.Entity("SCMS.Domain.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RoleId"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("RoleId");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            RoleName = "Student"
                        },
                        new
                        {
                            RoleId = 2,
                            RoleName = "CanteenStaff"
                        },
                        new
                        {
                            RoleId = 3,
                            RoleName = "CanteenManager"
                        },
                        new
                        {
                            RoleId = 4,
                            RoleName = "SystemAdmin"
                        },
                        new
                        {
                            RoleId = 5,
                            RoleName = "Parent"
                        },
                        new
                        {
                            RoleId = 6,
                            RoleName = "HeadTeacher"
                        },
                        new
                        {
                            RoleId = 7,
                            RoleName = "SchoolAdministration"
                        });
                });

            modelBuilder.Entity("SCMS.Domain.Transaction", b =>
                {
                    b.Property<int>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TransactionId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int?>("OrderId")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<int>("WalletId")
                        .HasColumnType("integer");

                    b.HasKey("TransactionId");

                    b.HasIndex("OrderId");

                    b.HasIndex("WalletId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("SCMS.Domain.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("HeadTeacherId")
                        .HasColumnType("integer");

                    b.Property<bool>("MustChangePassword")
                        .HasColumnType("boolean");

                    b.Property<int?>("ParentId")
                        .HasColumnType("integer");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordResetToken")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ResetTokenExpires")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.HasKey("UserId");

                    b.HasIndex("HeadTeacherId");

                    b.HasIndex("ParentId");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            CreatedAt = new DateTime(2026, 1, 6, 8, 43, 52, 731, DateTimeKind.Utc).AddTicks(4142),
                            Email = "admin@scms.com",
                            FullName = "System Administrator",
                            MustChangePassword = false,
                            PasswordHash = "$2a$11$GCjcwloeBKTpbGS20N9Fdeo8PtHRT8.oUErEBRj2SVwWAkK6Ag0R.",
                            RoleId = 4
                        },
                        new
                        {
                            UserId = 2,
                            CreatedAt = new DateTime(2026, 1, 6, 8, 43, 52, 937, DateTimeKind.Utc).AddTicks(9859),
                            Email = "canteenmanager@scms.com",
                            FullName = "Canteen Manager",
                            MustChangePassword = false,
                            PasswordHash = "$2a$11$0SNodnuFKpAv2cJyye4kgOGAg7qxlWkqcToNPeMS5cUGBZEPDC.s2",
                            RoleId = 3
                        },
                        new
                        {
                            UserId = 6,
                            CreatedAt = new DateTime(2026, 1, 6, 8, 43, 53, 166, DateTimeKind.Utc).AddTicks(9577),
                            Email = "student@scms.com",
                            FullName = "Nhat Dung",
                            MustChangePassword = false,
                            PasswordHash = "$2a$11$DeWWFU2/8wxHQBhHuBxX9.6IaSESQARaiFbpIlYWP/tMcLnuafg0K",
                            RoleId = 1
                        },
                        new
                        {
                            UserId = 7,
                            CreatedAt = new DateTime(2026, 1, 6, 8, 43, 53, 388, DateTimeKind.Utc).AddTicks(2077),
                            Email = "staff@scms.com",
                            FullName = "Thien Truong",
                            MustChangePassword = false,
                            PasswordHash = "$2a$11$LY/GtJreAxOx7utvHu168eqgL6SOvGVDzmXKGtQx9I5kpVijPLLIO",
                            RoleId = 2
                        },
                        new
                        {
                            UserId = 15,
                            CreatedAt = new DateTime(2026, 1, 6, 8, 43, 53, 627, DateTimeKind.Utc).AddTicks(8346),
                            Email = "parent@scms.com",
                            FullName = "Default Parent",
                            MustChangePassword = false,
                            PasswordHash = "$2a$11$doWrYgFpOrDa1DL2F/9mfOXzgwRrFr//7OZyE6kllTdnXIdmFS3/a",
                            RoleId = 5
                        },
                        new
                        {
                            UserId = 16,
                            CreatedAt = new DateTime(2026, 1, 6, 8, 43, 53, 838, DateTimeKind.Utc).AddTicks(2694),
                            Email = "headteacher@scms.com",
                            FullName = "Default Head Teacher",
                            MustChangePassword = false,
                            PasswordHash = "$2a$11$4gZh8qBO3sy/4YY0GjaPzeKw5dBmlAu3ymjp6MKD2dWj4laRBFMve",
                            RoleId = 6
                        },
                        new
                        {
                            UserId = 17,
                            CreatedAt = new DateTime(2026, 1, 6, 8, 43, 54, 58, DateTimeKind.Utc).AddTicks(8018),
                            Email = "schooladmin@scms.com",
                            FullName = "School Admin User",
                            MustChangePassword = false,
                            PasswordHash = "$2a$11$QFmwZkTpjRYfvCt35ycScu0tE7t4YBJsgynUsbGsk28FBYOd1X95m",
                            RoleId = 7
                        });
                });

            modelBuilder.Entity("SCMS.Domain.Wallet", b =>
                {
                    b.Property<int>("WalletId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("WalletId"));

                    b.Property<decimal>("Balance")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("WalletId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Wallets");

                    b.HasData(
                        new
                        {
                            WalletId = 1,
                            Balance = 500000m,
                            UserId = 6
                        });
                });

            modelBuilder.Entity("SCMS.Domain.MenuItem", b =>
                {
                    b.HasOne("SCMS.Domain.Category", "Category")
                        .WithMany("MenuItems")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("SCMS.Domain.Notification", b =>
                {
                    b.HasOne("SCMS.Domain.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SCMS.Domain.Order", b =>
                {
                    b.HasOne("SCMS.Domain.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SCMS.Domain.OrderItem", b =>
                {
                    b.HasOne("SCMS.Domain.MenuItem", "MenuItem")
                        .WithMany("OrderItems")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SCMS.Domain.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MenuItem");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("SCMS.Domain.Transaction", b =>
                {
                    b.HasOne("SCMS.Domain.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId");

                    b.HasOne("SCMS.Domain.Wallet", "Wallet")
                        .WithMany()
                        .HasForeignKey("WalletId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("SCMS.Domain.User", b =>
                {
                    b.HasOne("SCMS.Domain.User", "HeadTeacher")
                        .WithMany()
                        .HasForeignKey("HeadTeacherId");

                    b.HasOne("SCMS.Domain.User", "Parent")
                        .WithMany("LinkedStudents")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SCMS.Domain.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HeadTeacher");

                    b.Navigation("Parent");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("SCMS.Domain.Wallet", b =>
                {
                    b.HasOne("SCMS.Domain.User", "User")
                        .WithOne("Wallet")
                        .HasForeignKey("SCMS.Domain.Wallet", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SCMS.Domain.Category", b =>
                {
                    b.Navigation("MenuItems");
                });

            modelBuilder.Entity("SCMS.Domain.MenuItem", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("SCMS.Domain.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("SCMS.Domain.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("SCMS.Domain.User", b =>
                {
                    b.Navigation("LinkedStudents");

                    b.Navigation("Wallet")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
